frr version 8.5
frr defaults traditional
hostname r3
log syslog informational
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.23.2/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.13.2/30
 ip ospf area 0
 ip ospf cost 100
!
interface eth3
 ip address 192.168.3.1/24
!
interface lo
 ip address 10.255.0.3/32
 ip ospf area 0
!
router ospf
 ospf router-id 10.255.0.3
 passive-interface eth3
!
router bgp 65000
 bgp router-id 10.255.0.3
 no bgp default ipv4-unicast
 neighbor 10.255.0.1 remote-as 65000
 neighbor 10.255.0.1 update-source lo
 neighbor 10.255.0.2 remote-as 65000
 neighbor 10.255.0.2 update-source lo
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 10.255.0.1 activate
  neighbor 10.255.0.1 next-hop-self
  neighbor 10.255.0.2 activate
  neighbor 10.255.0.2 next-hop-self
 exit-address-family
!
line vty
!
