frr version 8.5
frr defaults traditional
hostname r2
log syslog informational
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.12.2/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.23.1/30
 ip ospf area 0
!
interface lo
 ip address 10.255.0.2/32
 ip ospf area 0
!
router ospf
 ospf router-id 10.255.0.2
!
router bgp 65000
 bgp router-id 10.255.0.2
 no bgp default ipv4-unicast
 neighbor 10.255.0.1 remote-as 65000
 neighbor 10.255.0.1 update-source lo
 neighbor 10.255.0.3 remote-as 65000
 neighbor 10.255.0.3 update-source lo
 !
 address-family ipv4 unicast
  neighbor 10.255.0.1 activate
  neighbor 10.255.0.1 next-hop-self
  neighbor 10.255.0.3 activate
  neighbor 10.255.0.3 next-hop-self
 exit-address-family
!
line vty
!
